### ISSUE TITLE
v0.3.0 fails to run from inside docker container

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-cli-plugin-ssr#31]
v0.3.0 works fine in bare linux/windows environments, but fails to run from inside docker contains. Here is how to reproduce:

1. make sure docker for linux/windows is installed on host
1. `vue create test` with mininal configs (only choosing `router` is enough)
1. `cd test && vue add @akryum/ssr`
1. put the following `docker-compose.yml` in the root folder of the created `test` project: 

    ```yml
    version: '3.7'
  
    services:
      test:
        container_name: 'test'
        image: node:8
        volumes:
          - .:/test
        working_dir: /test
        ports:
          - '8000:8000'
        restart: always
        command: ['node', './node_modules/@vue/cli-service/bin/vue-cli-service.js', 'ssr:serve']
   ```

1. run `docker-compose up -d`
1. run `docker exec -it test curl localhost:8000` and see the ssr running correctly inside the docker
1. however, run `curl localhost:8000` directly from host getting `curl: (52) Empty reply from server`, despite that we already use `ports: - '8000:8000'` to forward the http service from the container out to the host.

why I think it's a bug for v0.3.0:

1. simply change the last line of the `docker-compose.yml` to

   ```
    command: ['node', './node_modules/@vue/cli-service/bin/vue-cli-service.js', 'serve', '--port', '8000']
    ```
    and then `curl localhost:8000`  works;
2. simply installing v0.2.3 instead of v0.3.0 fixes it, too.
